---
# Tasks file for install Docker

- name: Gitflic | Update apt cache
  become: true
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  ignore_errors: true

- name: Gitflic | Install docker
  become: true
  ansible.builtin.apt:
    name: 
      - docker
      - docker-compose
    state: latest